### ISSUE TITLE
Using old Apple push API?

### ISSUE THREAD

**Issue by jrhone** [joaobarbosa/onesignal-python#3]
Hey João, this isn't technically a bug bit I'm hoping you can help.  Getting a push notification error on send

```
    "response": {
        "errors": ["Data Data must be no more than 2048 bytes long"]
    },
    "msg": "Failed sending push notification"
}
```

However the max payload size with apple's HTTP/2 push api is 4096 bytes, and OneSignal says 
```
We are now sending 100% of iOS and Safari Push Notifications through this new backend using Apple's brand new HTTP/2 API. 
Notification delivery for Web Push, Android (GCM) and other platforms will be migrated to the new backend in the following weeks.
```

Any idea? Should I file this with OneSignal?

**Comment by joaobarbosa** [comment]
I guess you should file this with OneSignal... The library just uses its rest api, so any kind of limit is placed there. :/ Sorry I couldn't help!
