### ISSUE TITLE
Can this lib work with latest requests version?

### ISSUE THREAD

**Issue by yarodevuci** [joaobarbosa/onesignal-python#5]
I am getting this error
`onesignal-python 0.1.0.dev1 has requirement requests==2.12.1, but you'll have requests 2.18.4 which is incompatible.`

I need latest **requests** version. Any help?

**Comment by joaobarbosa** [comment]
@yarodevuci I've been without enough time to keep this update, but I will try to take a look. If you want to take a look also, PRs are always welcome! :)

**Comment by yarodevuci** [comment]
@joaobarbosa sounds good. Thanks!

**Comment by ulgens** [comment]
This issue is resolved by #6
